---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ssl-vault::default]
  attributes: 
    dev_mode: true
    ssl-vault:
        certificates: ["example.com"]
